services:
  verifier:
    build:
      context: ..
      dockerfile: Dockerfile.local
    image: ${VERIFIER_BACKEND_IMAGE:-verifier-backend:local}
    container_name: ${VERIFIER_BACKEND_CONTAINER_NAME:-verifier-backend}
    ports:
      - "${VERIFIER_BACKEND_HOST_PORT:-8080}:8080"
    environment:
      VERIFIER_PUBLICURL: ${VERIFIER_PUBLIC_URL:-https://localhost}
      VERIFIER_IRISHLIFE_CUSTOMERBASEURL: ${VERIFIER_IRISHLIFE_CUSTOMERBASEURL:-https://localhost}
      VERIFIER_IRISHLIFE_PIDISSUERCHAIN_PATH: ${VERIFIER_IRISHLIFE_PIDISSUERCHAIN_PATH:-file:/opt/verifier/local-issuer-certs/PID-DS-LOCAL-UT_cert.pem}
      VERIFIER_CLIENTMETADATA_VPFORMATS_MSOMDOC_ENABLED: ${VERIFIER_CLIENTMETADATA_VPFORMATS_MSOMDOC_ENABLED:-true}
      VERIFIER_REQUESTJWT_EMBED: ByReference
      VERIFIER_REQUESTJWT_REQUESTURIMETHOD: Get
      VERIFIER_RESPONSE_MODE: DirectPost
      VERIFIER_AUTHORIZATIONREQUESTSCHEME: haip-vp
      MANAGEMENT_HEALTH_MAIL_ENABLED: ${MANAGEMENT_HEALTH_MAIL_ENABLED:-false}
    volumes:
      - ${VERIFIER_PID_ISSUER_CERT_DIR:-./local/certs}:/opt/verifier/local-issuer-certs:ro

  verifier-ui:
    build:
      context: ../../eudi-web-verifier
      dockerfile: Dockerfile
    image: ${VERIFIER_UI_IMAGE:-eudi-web-verifier:local}
    container_name: ${VERIFIER_UI_CONTAINER_NAME:-verifier-ui}
    depends_on:
      - verifier
    ports:
      - "${VERIFIER_UI_HOST_PORT:-4300}:4300"
    environment:
      HOST_API: ${VERIFIER_PUBLIC_URL:-https://localhost}

  haproxy:
    image: haproxy:2.7.2
    container_name: ${VERIFIER_HAPROXY_CONTAINER_NAME:-verifier-haproxy}
    depends_on:
      - verifier
      - verifier-ui
    ports:
      - "${VERIFIER_TLS_HOST_PORT:-443}:443"
    volumes:
      - ${VERIFIER_HAPROXY_CONFIG_FILE:-./haproxy.conf}:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./local/certs/haproxy-local.pem:/etc/ssl/certs/mysite.pem:ro